### ISSUE TITLE
More questions about localization and tracking

### ISSUE THREAD

**Issue by Haotian-Zhang** [krrish94/ICRA2017#1]
Hi, thank you so much for the code release! They are quite helpful! 

As shown in the example image, we can not only see the 2D prior shape but also we can convert it to 3D and know its distance in the monocular scene. In addition, we can know the id of the observed car. I think ground plane estimation and some tracking algorithm is used here, could you please tell us more about it?

Thank you so much!

**Comment by krrish94** [comment]
Thanks for your interest!

The overall pipeline to get to the kind of results shown in the main image is a bit involved. This repo contains the most crucial part of that pipeline: single image-based shape (wireframe-model) and pose estimation. On top of this, we built a multi-view optimization algorithm, supported by a multi-object tracking algorithm ( https://github.com/JunaidCS032/MOTBeyondPixels ).

You could take a look at some of our papers to know more, particularly those from ICRA/IROS 2017,2018. ( https://krrish94.github.io/publications/ ). Feel free to reach out with questions, if any.
