### ISSUE TITLE
Do I need intrinsics matrix if I want to run in my own image?

### ISSUE THREAD

**Issue by ChenMinQi** [krrish94/ICRA2017#3]
It seems that i must have camera intrinsics if i want to run in my own image?
If I just want to draw 2D wireframe, it seeems  camera intrinsics is not necessary?

**Comment by JunaidCS032** [comment]
You have to use the intrinsic of the camera from which the image has been captured.

2D wireframe is a projection of the 3D wireframe. And to project the 3D wireframe you require the camera intrinsic.

Best.

**Comment by JunaidCS032** [comment]
You have to use the intrinsic of the camera from which the image has been captured.

2D wireframe is a projection of the 3D wireframe. And to project the 3D wireframe you require the camera intrinsic.

Best.
