### ISSUE TITLE
Training on custom data

### ISSUE THREAD

**Issue by pavan4** [krrish94/ICRA2017#5]
Is there any plan to release dataset, training code for the keypoint network (modified stacked hourglass)? The keypoint network currently is written in torch, which is deprecated. Are there plans to rewrite this in another framework, say pytorch? Asking because, if not, I could possibly look into it. 

Secondly, is there any plan to update the repo on how to customize for objects such as chair, laptop etc., which was mentioned in the write up?

**Comment by krrish94** [comment]
Hi @pavan4 

Thanks for your interest in this work. As yet, there aren't plans in place to port the Lua torch implementation to pytorch. But I'd be happy to assist, merge (and ofc credit) if anyone's willing to take that up.

As for the second question, we've managed to run this scheme on chairs and laptops, then again, the lua torch issues persist. I haven't yet figured out a way to polish and release all of that.
