### ISSUE TITLE
OSError: cache/poseAdjusterOutput.txt not found.

### ISSUE THREAD

**Issue by Robotzeroo** [krrish94/ICRA2017#6]
When I run "demo.py" I get the following error, do you know what is the cause and how should I fix it? Thank you very much for your help and contribution!

F0522 02:57:01.814723 28287 rotation.h:591] Check failed: pt != result (0x7ffe6a9637f0 vs. 0x7ffe6a9637f0) Inplace rotation is not supported.
*** Check failure stack trace: ***
    @     0x7fee72d480cd  google::LogMessage::Fail()
    @     0x7fee72d49f33  google::LogMessage::SendToLog()
    @     0x7fee72d47c28  google::LogMessage::Flush()
    @     0x7fee72d4a999  google::LogMessageFatal::~LogMessageFatal()
    @     0x556a855040c9  (unknown)
    @     0x556a85502dad  (unknown)
    @     0x556a85501d78  (unknown)
    @     0x556a85500df4  (unknown)
    @     0x556a85500092  (unknown)
    @     0x556a854ff5c1  (unknown)
    @     0x556a854feb89  (unknown)
    @     0x556a855214c6  (unknown)
    @     0x556a855473f6  (unknown)
    @     0x556a85535119  (unknown)
    @     0x556a85548f67  (unknown)
    @     0x556a8555b0ed  (unknown)
    @     0x556a8555bb82  (unknown)
    @     0x556a85560604  (unknown)
    @     0x556a8552f0e6  (unknown)
    @     0x556a8552fc99  (unknown)
    @     0x556a854f98df  (unknown)
    @     0x7fee70e2cbf7  __libc_start_main
    @     0x556a854f907a  (unknown)
Traceback (most recent call last):
  File "demo.py", line 279, in <module>
    predictedPose = np.loadtxt(poseAdjusterOutput)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 968, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: cache/poseAdjusterOutput.txt not found.

**Comment by moshanATucsd** [comment]
This seems to be related to Ceres, especially https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/rotation.h, I am not sure how this happened but perhaps you need to check the Ceres installation.
